project_name: FGVC-EX-SOD
notes: 'no inverse'
exp_name: spvsmv1-nonoverla
use_wandb: True
wandb_entity: libicheng
train_root: ./CUB200-2011/train/
val_root: ./CUB200-2011/test/
data_root: ./CUB200-2011/
isU2net: True
coeff_max: 0.3
#"CUB", "dogs", "nabirds"
dataset: CUB
img_size: 448
num_workers: 2
batch_size: 4
model_name: vit-b_16
seed: 1
pretrained: ~
optimizer: SGD
max_lr: 0.00049
wdecay: 0.0003
max_epochs: 80
warmup_batchs: 1500
use_amp: True
isSOD: True
padding: True
#fpn_size: 1536
use_selection: True
num_classes: 200
split: 'non-overlap'
#num_selects:
#  layer1: 256
#  layer2: 128
#  layer3: 64
patch_num: 100
num_selects: 126
use_combiner: True
#lambda_b0: 1.375
#lambda_b: 0.3
#lambda_s: 0.0
#lambda_n: 5.0
#lambda_c: 1.0
lambda_b: 0.5
lambda_a: 0.2
update_freq: 2
log_freq: 100
eval_freq: 2
temperature: 64